// Seed data for the 253 canonical patterns from
// Christopher Alexander, Sara Ishikawa, Murray Silverstein et al.,
// "A Pattern Language" (Oxford University Press, 1977).
//
// Titles, numbers and scales are factual; summaries are our own short
// paraphrases and NOT copied from the book.

export type Scale = "town" | "building" | "construction";

export interface SeedPattern {
  number: number;
  title: string;
  slug: string;
  scale: Scale;
  summary: string;
}

const slugify = (n: number, t: string) =>
  `${n.toString().padStart(3, "0")}-${t
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")}`;

const raw: [number, string, Scale, string][] = [
  // ── TOWNS ────────────────────────────────────────────────
  [1, "Independent Regions", "town", "Large regions should govern themselves, small enough that people can identify with them."],
  [2, "The Distribution of Towns", "town", "Distribute settlements of all sizes evenly across a region so no area is starved or overwhelmed."],
  [3, "City Country Fingers", "town", "Interlock country and city so no home is more than a few minutes from open land."],
  [4, "Agricultural Valleys", "town", "Protect fertile valleys absolutely; build only on the hills and ridges around them."],
  [5, "Lace of Country Streets", "town", "Rural roads form a loose lacework, not a grid, following the land and connecting hamlets."],
  [6, "Country Towns", "town", "Keep small country towns alive by supporting their local economies instead of absorbing them."],
  [7, "The Countryside", "town", "All land outside cities belongs to the common wild — tended, not owned for exclusion."],
  [8, "Mosaic of Subcultures", "town", "A city is strongest when it is a patchwork of distinct small subcultures, each with its own character."],
  [9, "Scattered Work", "town", "Workplaces should be sprinkled throughout the city, not zoned away into a distant district."],
  [10, "Magic of the City", "town", "Everyone needs occasional access to the dense, strange, intense center of a real metropolis."],
  [11, "Local Transport Areas", "town", "Define zones where local travel happens on foot, bike, or low-speed vehicle, with cars excluded."],
  [12, "Community of 7000", "town", "Political community at around seven thousand people — small enough for voices to carry."],
  [13, "Subculture Boundary", "town", "Thick, functional boundaries between subcultures keep them from dissolving each other."],
  [14, "Identifiable Neighborhood", "town", "People need a neighborhood they can name, whose edges and center they know."],
  [15, "Neighborhood Boundary", "town", "A neighborhood becomes real only when its boundary is more than a line on a map."],
  [16, "Web of Public Transportation", "town", "Public transit should weave a continuous web, not a few disconnected trunk lines."],
  [17, "Ring Roads", "town", "Use ring roads to keep through-traffic out of living areas while still letting it move freely."],
  [18, "Network of Learning", "town", "Learning happens everywhere; spread small schools, workshops and masters across the city."],
  [19, "Web of Shopping", "town", "Distribute shops to match where people actually walk, not to force them into malls."],
  [20, "Mini-Buses", "town", "Small, flexible buses that respond to demand serve neighborhoods better than rigid routes."],
  [21, "Four-Story Limit", "town", "No building more than four stories tall — people lose touch with the ground above that."],
  [22, "Nine Per Cent Parking", "town", "Never give more than nine per cent of a district's land to parking."],
  [23, "Parallel Roads", "town", "A few parallel through-roads are better than one wide artery that splits a neighborhood."],
  [24, "Sacred Sites", "town", "Every locality has sites of historical or spiritual meaning; protect and acknowledge them."],
  [25, "Access to Water", "town", "Keep the edges of rivers, lakes and seas public and walkable."],
  [26, "Life Cycle", "town", "A community holds every stage of life, from birth to death, visibly together."],
  [27, "Men and Women", "town", "Balance the rhythms of men's and women's lives in the public and domestic space of a town."],
  [28, "Eccentric Nucleus", "town", "Each community has a slightly off-center heart of intense activity, not a symmetric center."],
  [29, "Density Rings", "town", "Density falls off in rings from the center, gradually, without hard edges."],
  [30, "Activity Nodes", "town", "Concentrate public activities at a few nodes, close together, so each amplifies the others."],
  [31, "Promenade", "town", "A place for people to walk back and forth in the evening, seeing and being seen."],
  [32, "Shopping Street", "town", "A shopping street has shops on both sides, narrow enough to see across."],
  [33, "Night Life", "town", "Cluster nighttime places so that nobody walks alone through dark empty streets."],
  [34, "Interchange", "town", "Transit interchanges work only if you can walk between lines without detours or barriers."],
  [35, "Household Mix", "town", "A neighborhood mixes households of every size, age and income."],
  [36, "Degrees of Publicness", "town", "Housing is arranged so that some is intensely public and some deeply private, with everything between."],
  [37, "House Cluster", "town", "Houses group in clusters of 8–12 around a shared place."],
  [38, "Row Houses", "town", "Row houses fit where small plots abut; share walls but give each its own face."],
  [39, "Housing Hill", "town", "At higher densities, step housing up a slope so everyone still gets ground, light and a view."],
  [40, "Old People Everywhere", "town", "Old people must live among the young; isolate them and they wither."],
  [41, "Work Community", "town", "Workplaces group into communities of 10–20 where people know each other's work."],
  [42, "Industrial Ribbon", "town", "Industrial land forms ribbons along rail and river, accessible but not imposing on housing."],
  [43, "University as a Marketplace", "town", "Open the university onto the city; let courses and workshops mix with shops and cafes."],
  [44, "Local Town Hall", "town", "Every 7,000-person community has its own modest town hall, not a remote municipal building."],
  [45, "Necklace of Community Projects", "town", "Around the town hall, a ring of small civic projects people can actually join."],
  [46, "Market of Many Shops", "town", "A market is many small shops under one loose roof, not a single supermarket."],
  [47, "Health Center", "town", "Health care is a small neighborhood center for keeping well, not a distant hospital for emergencies."],
  [48, "Housing In Between", "town", "Housing belongs everywhere — between offices, shops, workshops — not in separate tracts."],
  [49, "Looped Local Roads", "town", "Local roads loop so no street becomes a shortcut for strangers."],
  [50, "T Junctions", "town", "Prefer T-junctions to crossroads; traffic slows, buildings face the intersection."],
  [51, "Green Streets", "town", "Most local streets can be narrow green lanes with grass and trees, not paved throughways."],
  [52, "Network of Paths and Cars", "town", "Weave walking paths and car roads in separate but intersecting webs."],
  [53, "Main Gateways", "town", "Mark every district's entrance with a gateway you can feel as you pass through."],
  [54, "Road Crossing", "town", "Design road crossings so that pedestrians, not cars, dominate."],
  [55, "Raised Walk", "town", "Where cars and people must share space, raise the walkway a handspan above the road."],
  [56, "Bike Paths and Racks", "town", "Give bikes their own continuous paths and a place to lock up at every destination."],
  [57, "Children in the City", "town", "Children need to move through the whole city on their own, safely."],
  [58, "Carnival", "town", "Every city needs a season of carnival — open, unruly, participatory."],
  [59, "Quiet Backs", "town", "Behind the busiest places, always leave a quiet back for retreat."],
  [60, "Accessible Green", "town", "Green open space within three minutes' walk of every home."],
  [61, "Small Public Squares", "town", "Public squares work best when they are small — 60 feet across, not acres."],
  [62, "High Places", "town", "Every district has a high place to climb, from which you can see the whole."],
  [63, "Dancing in the Street", "town", "Leave room, and reason, for people to dance in the street together."],
  [64, "Pools and Streams", "town", "Keep water visible, walkable-to, and touchable in the fabric of the town."],
  [65, "Birth Places", "town", "Small local places where women give birth among family and neighbors, not distant hospitals."],
  [66, "Holy Ground", "town", "A place for the dead, the sacred, or the transcendent — within every community."],
  [67, "Common Land", "town", "Every house has access to a piece of common land, held and used in common."],
  [68, "Connected Play", "town", "Children's play space must connect — one yard to the next — into a continuous territory."],
  [69, "Public Outdoor Room", "town", "Make outdoor rooms where groups can gather at all hours, not just passageways."],
  [70, "Grave Sites", "town", "Small grave sites, nearby, so the dead stay part of community life."],
  [71, "Still Water", "town", "Still water — a pond, a reflecting pool — settles the nerves of a place."],
  [72, "Local Sports", "town", "Small local sports fields within walking distance, not distant stadiums."],
  [73, "Adventure Playground", "town", "Children need places they can rebuild with their own hands; not polished playgrounds."],
  [74, "Animals", "town", "Animals must be present in the city — for children, for food, for company."],
  [75, "The Family", "town", "Households should support family in its many real forms, not the idealized nuclear one."],
  [76, "House for a Small Family", "town", "A small family needs enough common space that it doesn't squeeze itself apart."],
  [77, "House for a Couple", "town", "A couple's house must protect intimacy without locking them into a single room."],
  [78, "House for One Person", "town", "A house for one person is a whole tiny world — not a compromised apartment."],
  [79, "Your Own Home", "town", "Every family needs a home it can shape over time, not a rental it can't change."],
  [80, "Self-Governing Workshops and Offices", "town", "Small workplaces governed by the people who work there, not owned from elsewhere."],
  [81, "Small Services Without Red Tape", "town", "Government services should be storefronts a person can walk into — not remote bureaucracies."],
  [82, "Office Connections", "town", "Connect offices so people walk through each other's work and meet at the edges."],
  [83, "Master and Apprentices", "town", "Workshops where older workers teach by doing, with younger ones alongside them."],
  [84, "Teenage Society", "town", "Teenagers need their own half-independent society, visible to but not owned by adults."],
  [85, "Shopfront Schools", "town", "Small schools in shopfronts on the street, not isolated campuses behind fences."],
  [86, "Children's Home", "town", "For children without families, a small house and a few consistent adults — not an institution."],
  [87, "Individually Owned Shops", "town", "Support individually owned shops over chains — they give the street its character."],
  [88, "Street Cafe", "town", "Every neighborhood needs at least one cafe where you can sit outside and watch life go by."],
  [89, "Corner Grocery", "town", "Small groceries at the corners of neighborhoods, close enough to walk to for a single item."],
  [90, "Beer Hall", "town", "A large public room, warmly lit, where drinking is social and unhurried."],
  [91, "Traveler's Inn", "town", "Small inns where strangers and locals overlap — not anonymous chain hotels."],
  [92, "Bus Stop", "town", "Bus stops become small social places when they're sheltered and part of other activities."],
  [93, "Food Stands", "town", "Permanent street food stands scattered on busy corners."],
  [94, "Sleeping in Public", "town", "A humane city lets people sleep in public without criminalizing them."],
  // ── BUILDINGS ────────────────────────────────────────────
  [95, "Building Complex", "building", "Prefer many small buildings joined into a complex over one single giant building."],
  [96, "Number of Stories", "building", "Keep most buildings between one and four stories; go higher only for good reason."],
  [97, "Shielded Parking", "building", "Parking should be shielded from the street and the rooms that face it."],
  [98, "Circulation Realms", "building", "Break circulation into distinct realms that overlap, instead of endless corridors."],
  [99, "Main Building", "building", "A complex of buildings needs one main building that dominates in a clear way."],
  [100, "Pedestrian Street", "building", "Inside a complex, a central path becomes a pedestrian street lined with entrances."],
  [101, "Building Thoroughfare", "building", "When a building must be crossed, make the path through it a real street with shops and light."],
  [102, "Family of Entrances", "building", "Group the entrances of a complex into a family you can see all at once."],
  [103, "Small Parking Lots", "building", "Break parking into many small lots, never a single sea of asphalt."],
  [104, "Site Repair", "building", "Build on the worst part of the site, leaving the best parts alone."],
  [105, "South Facing Outdoors", "building", "Place important outdoor spaces to the south of the buildings that bound them."],
  [106, "Positive Outdoor Space", "building", "Outdoor space must feel like a shaped room, not leftover land."],
  [107, "Wings of Light", "building", "Build in long thin wings so every room gets daylight from two sides."],
  [108, "Connected Buildings", "building", "Link buildings to each other along their edges, not by corridors across gaps."],
  [109, "Long Thin House", "building", "The best houses are long and thin — every room has outdoor contact on at least one side."],
  [110, "Main Entrance", "building", "A main entrance must be visible from the way people first approach — not hidden."],
  [111, "Half-Hidden Garden", "building", "Place the main garden between the street and the house — half seen, half private."],
  [112, "Entrance Transition", "building", "Make a real transition of a few steps between street and front door: change of light, level, or direction."],
  [113, "Car Connection", "building", "Let the car reach the house gracefully without dominating the entrance."],
  [114, "Hierarchy of Open Space", "building", "Outdoor spaces nest: courtyard within yard, yard within neighborhood."],
  [115, "Courtyards Which Live", "building", "Courtyards need at least two entrances, a view out, and a reason to cross them."],
  [116, "Cascade of Roofs", "building", "Roofs cascade from the main ridge down to small sheltered edges."],
  [117, "Sheltering Roof", "building", "A roof must shelter not only the rooms but the feeling of the building beneath it."],
  [118, "Roof Garden", "building", "On flat roofs, make gardens people actually use."],
  [119, "Arcades", "building", "Arcades along building edges blur inside and outside."],
  [120, "Paths and Goals", "building", "Lay paths out to follow where people actually want to walk, not designer's lines."],
  [121, "Path Shape", "building", "Paths widen and narrow; they are places, not conveyors."],
  [122, "Building Fronts", "building", "Building fronts must face outward to the street — the front is a social act."],
  [123, "Pedestrian Density", "building", "Concentrate people in public space: 150 square feet per person feels alive, more feels empty."],
  [124, "Activity Pockets", "building", "Life happens at the edges of a space, in small pockets around the main flow."],
  [125, "Stair Seats", "building", "Where steps meet a public space, they become seats."],
  [126, "Something Roughly in the Middle", "building", "Every public space needs something roughly at its center to anchor activity."],
  [127, "Intimacy Gradient", "building", "Arrange rooms in a sequence from most public at the entrance to most private at the back."],
  [128, "Indoor Sunlight", "building", "Put the rooms where people spend the day on the sunny side."],
  [129, "Common Areas at the Heart", "building", "The common areas of a household sit at the heart where daily paths cross them."],
  [130, "Entrance Room", "building", "An entrance needs a real room, not a corridor — for taking off coats and greeting."],
  [131, "The Flow Through Rooms", "building", "Major rooms have two ways in so movement flows through, not to a dead end."],
  [132, "Short Passages", "building", "Keep corridors short, wide, and full of light; long dim passages kill a building."],
  [133, "Staircase as a Stage", "building", "The main stair is a small stage where people arrive and part."],
  [134, "Zen View", "building", "Frame a beautiful view so it must be sought — don't expose it all at once."],
  [135, "Tapestry of Light and Dark", "building", "Rooms alternate light and dark; one uniform brightness flattens everything."],
  [136, "Couple's Realm", "building", "A couple needs a realm of their own at one end of the house."],
  [137, "Children's Realm", "building", "Children need a cluster of small rooms and passages they can call theirs."],
  [138, "Sleeping to the East", "building", "Bedrooms face east to wake with the sun."],
  [139, "Farmhouse Kitchen", "building", "A large kitchen everyone eats and works in — not an efficient galley."],
  [140, "Private Terrace on the Street", "building", "Each dwelling has a small private terrace on the street, a half-step up."],
  [141, "A Room of One's Own", "building", "Every person in a household needs a room, however small, that is theirs alone."],
  [142, "Sequence of Sitting Spaces", "building", "A house has a sequence of sitting places, each with a different character."],
  [143, "Bed Cluster", "building", "Children's beds cluster in one room or wing, not in separate isolated bedrooms."],
  [144, "Bathing Room", "building", "A real bathing room — warm, with views out — not a windowless bathroom."],
  [145, "Bulk Storage", "building", "Set aside one big room or area for bulk storage — otherwise it eats into living space."],
  [146, "Flexible Office Space", "building", "Office layouts must be reconfigurable by the people who use them, on the day."],
  [147, "Communal Eating", "building", "Any group working together needs a place to eat together every day."],
  [148, "Small Work Groups", "building", "Subdivide an office into groups of 6–12 so conversation and overhearing work."],
  [149, "Reception Welcomes You", "building", "A reception must welcome, not process, arrivals."],
  [150, "A Place to Wait", "building", "Waiting places need quiet corners to think in, not just chairs in a row."],
  [151, "Small Meeting Rooms", "building", "Many small meeting rooms work better than one big conference room."],
  [152, "Half-Private Office", "building", "Offices are half-open — not private cells nor open plan — so people can choose engagement."],
  [153, "Rooms to Rent", "building", "Every neighborhood has rooms you can rent for a month or a year — lodgings, not hotels."],
  [154, "Teenager's Cottage", "building", "Give teenagers a small cottage or attached room with its own entrance."],
  [155, "Old Age Cottage", "building", "Old people need a cottage close to family, not folded into a spare bedroom."],
  [156, "Settled Work", "building", "Work at home in a part of the house set up for it, not in a corner of the kitchen table."],
  [157, "Home Workshop", "building", "Every house has a small workshop for making and mending."],
  [158, "Open Stairs", "building", "Stairs are open to the rooms they serve, not hidden behind doors."],
  [159, "Light on Two Sides of Every Room", "building", "Every room worth being in has windows on at least two sides."],
  [160, "Building Edge", "building", "The edge of a building is a place to live — not just a wall."],
  [161, "Sunny Place", "building", "Make a sunny outdoor spot just outside the most-used room."],
  [162, "North Face", "building", "The north face of a building is a cool working side; put workshops, storage, laundry there."],
  [163, "Outdoor Room", "building", "Build outdoor rooms with real walls of hedge or trellis, a ceiling of leaves, and a floor."],
  [164, "Street Windows", "building", "Windows on the street carry the life of the house outward."],
  [165, "Opening to the Street", "building", "Ground-floor rooms open directly to the street where possible."],
  [166, "Gallery Surround", "building", "A gallery surrounding the upper floor gives life to every room on it."],
  [167, "Six-Foot Balcony", "building", "Balconies must be at least six feet deep to be usable; shallower ones are empty."],
  [168, "Connection to the Earth", "building", "A building touches the earth; keep its lowest floor close to the ground."],
  [169, "Terraced Slope", "building", "On slopes, build terraces — plants and people need level ground."],
  [170, "Fruit Trees", "building", "Plant fruit trees near the house — they combine beauty, shade, and food."],
  [171, "Tree Places", "building", "Make tree places: each tree a room with seating beneath it."],
  [172, "Garden Growing Wild", "building", "Leave part of every garden to grow wild."],
  [173, "Garden Wall", "building", "A low wall makes a garden a garden; without it, it's just yard."],
  [174, "Trellised Walk", "building", "A trellis-covered walk is the best transition between buildings and gardens."],
  [175, "Greenhouse", "building", "Every house gets a small greenhouse — a room for winter plants and warmth."],
  [176, "Garden Seat", "building", "A garden needs a single quiet seat where one person can sit and be alone."],
  [177, "Vegetable Garden", "building", "Vegetable gardens belong close to the kitchen, not at the far end of the yard."],
  [178, "Compost", "building", "A compost heap where kitchen and garden meet."],
  [179, "Alcoves", "building", "Every large room needs alcoves — small bays where one or two people can nest apart."],
  [180, "Window Place", "building", "Every room needs a place at a window to sit, read, or stare out."],
  [181, "The Fire", "building", "A fire — real or apparent — is the heart of a house."],
  [182, "Eating Atmosphere", "building", "Eating places must hold the light low, the space snug, around the table."],
  [183, "Workspace Enclosure", "building", "A workspace is enclosed on at least two sides, open on the other two."],
  [184, "Cooking Layout", "building", "The cook must see out, see in, and work along a continuous surface."],
  [185, "Sitting Circle", "building", "Sitting places work when chairs make a rough circle, not a line."],
  [186, "Communal Sleeping", "building", "Some groups live better when they sleep together in one big room."],
  [187, "Marriage Bed", "building", "The marriage bed is an anchor; give it weight, light, and a room of its own."],
  [188, "Bed Alcove", "building", "A bed should be in an alcove, not a loose object in an empty room."],
  [189, "Dressing Room", "building", "A real dressing room, however small, beats a closet in a bedroom."],
  [190, "Ceiling Height Variety", "building", "Vary ceiling height room to room — not every room wants the same height."],
  [191, "The Shape of Indoor Space", "building", "Indoor rooms want irregular shapes that respond to use, not perfect rectangles."],
  [192, "Windows Overlooking Life", "building", "Put windows where they overlook life, not parking lots or blank walls."],
  [193, "Half-Open Wall", "building", "Walls between rooms are best when partially open — a half-wall, a sideways doorway, an opening overhead."],
  [194, "Interior Windows", "building", "Interior windows connect rooms to each other when outer windows alone can't."],
  [195, "Staircase Volume", "building", "Treat the staircase as a three-dimensional volume, not a diagonal of wasted space."],
  [196, "Corner Doors", "building", "Doors in the corner of a room leave the walls free for furniture."],
  [197, "Thick Walls", "building", "Make the walls thick enough to hold shelves, nooks and window seats in them."],
  [198, "Closets Between Rooms", "building", "Use closets as acoustic barriers between rooms."],
  [199, "Sunny Counter", "building", "The kitchen counter belongs under a sunny window."],
  [200, "Open Shelves", "building", "Most of what you own should be on open shelves, visible and accessible."],
  [201, "Waist-High Shelf", "building", "A continuous shelf at waist height along a room wall gathers life."],
  [202, "Built-In Seats", "building", "Built-in seats along windows and walls turn edges into living places."],
  [203, "Child Caves", "building", "Children need caves — small enclosures they can crawl into, under a stair or in a wall."],
  [204, "Secret Place", "building", "Every house needs one secret place — a small hidden room, chamber, or cupboard."],
  // ── CONSTRUCTION ─────────────────────────────────────────
  [205, "Structure Follows Social Spaces", "construction", "Let the structural plan emerge from the social plan, not the reverse."],
  [206, "Efficient Structure", "construction", "Efficient structure tapers to bearings; fat where load is greatest, thin where it isn't."],
  [207, "Good Materials", "construction", "Choose materials that age well, can be worked by hand, and can be repaired in place."],
  [208, "Gradual Stiffening", "construction", "Build loose, then stiffen as you know the building is right — don't lock in early."],
  [209, "Roof Layout", "construction", "Lay the roof out to follow the rooms beneath it."],
  [210, "Floor and Ceiling Layout", "construction", "Each floor's structure follows the rooms above and below, not a rigid grid."],
  [211, "Thickening the Outer Walls", "construction", "The outer walls hold life — thicken them for windows, shelves, seats."],
  [212, "Columns at the Corners", "construction", "Place structural columns at the corners of rooms, not through them."],
  [213, "Final Column Distribution", "construction", "Distribute columns along walls until the building can stand — then stop."],
  [214, "Root Foundations", "construction", "Foundations should root into the ground — broad feet, not narrow stilts."],
  [215, "Ground Floor Slab", "construction", "Make the ground floor a real mass — a slab that ties the building to the earth."],
  [216, "Box Columns", "construction", "Build columns as hollow boxes that can be filled with wiring, plumbing, or shelves."],
  [217, "Perimeter Beams", "construction", "Perimeter beams tie the building together at every floor."],
  [218, "Wall Membrane", "construction", "Walls are membranes between columns — skin, not structure."],
  [219, "Floor-Ceiling Vaults", "construction", "Build floors and ceilings as shallow vaults — they carry load far better than slabs."],
  [220, "Roof Vaults", "construction", "Roofs can be vaulted too; vaults are easier to build and feel than flat roofs."],
  [221, "Natural Doors and Windows", "construction", "Don't pre-fabricate all openings — leave room to place them where light and view invite."],
  [222, "Low Sill", "construction", "Window sills belong low — 12 to 14 inches — so you can see out while sitting."],
  [223, "Deep Reveals", "construction", "Reveal the thickness of walls at windows — it softens the light."],
  [224, "Low Doorway", "construction", "A low doorway at a threshold slows you down and marks arrival."],
  [225, "Frames as Thickened Edges", "construction", "Door and window frames are thickened edges — give them real depth."],
  [226, "Column Place", "construction", "Each column makes a small place around it — recognize it, don't hide it."],
  [227, "Column Connection", "construction", "Columns connect to what they carry through a visible capital — not a sharp line."],
  [228, "Stair Vault", "construction", "Build the stair as a vault — it's self-supporting and it thickens the wall it rises against."],
  [229, "Duct Space", "construction", "Leave continuous duct space where wires and pipes can be added or replaced later."],
  [230, "Radiant Heat", "construction", "Heat is best when it radiates from large warm surfaces — floors, walls — not from blowing air."],
  [231, "Dormer Windows", "construction", "Dormers turn an attic into a room."],
  [232, "Roof Caps", "construction", "A cap or lantern at the highest point of the roof finishes the form."],
  [233, "Floor Surface", "construction", "Floors shift surface between rooms — hard near entrances, soft near sitting."],
  [234, "Lapped Outside Walls", "construction", "Outer walls lap and weather in layers, not flush cladding."],
  [235, "Soft Inside Walls", "construction", "Inside walls are best when slightly soft to the touch — plaster, wood, not hard gypsum."],
  [236, "Windows Which Open Wide", "construction", "Windows should open fully — at least half their area, not a small hopper."],
  [237, "Solid Doors with Glass", "construction", "Main doors are solid with a pane of glass — you can see and still shut."],
  [238, "Filtered Light", "construction", "Filter direct sun through leaves, lattice, or trellis; raw sun is blinding."],
  [239, "Small Panes", "construction", "Break large panes into small ones — the light pattern is livelier and scale is human."],
  [240, "Half-Inch Trim", "construction", "Trim elements at half-inch increments — thick enough to hold a shadow line."],
  [241, "Seat Spots", "construction", "Every outdoor space has spots where sitting feels natural — mark them with real seats."],
  [242, "Front Door Bench", "construction", "A bench beside the front door welcomes arrivals and lingerers."],
  [243, "Sitting Wall", "construction", "Low walls at seat height double as seats wherever they run."],
  [244, "Canvas Roofs", "construction", "Canvas roofs shelter outdoor rooms in summer, roll back in winter."],
  [245, "Raised Flowers", "construction", "Raise flower beds to waist height so they can be tended and smelled."],
  [246, "Climbing Plants", "construction", "Grow climbing plants on walls and trellises — they cool, shade, and soften buildings."],
  [247, "Paving with Cracks Between the Stones", "construction", "Leave cracks in paving for grass and insects — a living floor."],
  [248, "Soft Tile and Brick", "construction", "Use soft, hand-made tile and brick; machine-hard surfaces never acquire life."],
  [249, "Ornament", "construction", "Ornament where edges meet — not pasted on, but at real joints."],
  [250, "Warm Colors", "construction", "Warm colors on indoor surfaces — cool colors only accent them."],
  [251, "Different Chairs", "construction", "Never furnish with identical chairs — every chair should be itself."],
  [252, "Pools of Light", "construction", "Light rooms in pools — several small lights, not one uniform ceiling fixture."],
  [253, "Things from Your Life", "construction", "Fill a house with objects from your own life, not decorator's choices."],
];

export const PATTERNS: SeedPattern[] = raw.map(([number, title, scale, summary]) => ({
  number,
  title,
  scale,
  summary,
  slug: slugify(number, title),
}));

// Connections: the patterns are described in the book as pointing both to
// "larger" patterns they help to complete and "smaller" patterns that help to
// complete them. The edge list below is a curated subset of those structural
// relationships — enough to render a richly-connected graph. We store edges
// as [fromNumber, toNumber] and treat them as "related" in both directions.
export const CONNECTIONS: [number, number][] = [
  // Towns → sub-regions
  [1, 2], [1, 3], [2, 3], [2, 6], [3, 4], [3, 5], [3, 7],
  [4, 7], [5, 6], [5, 7], [6, 7], [6, 87], [6, 88],
  // Cities & subcultures
  [8, 13], [8, 14], [8, 42], [8, 12], [9, 41], [9, 42], [9, 80], [10, 30], [10, 33], [10, 58],
  [11, 17], [11, 22], [11, 49], [11, 52], [12, 13], [12, 14], [12, 44], [12, 45],
  [13, 14], [13, 15], [14, 15], [14, 16], [14, 35], [14, 37], [14, 60],
  [16, 17], [16, 20], [16, 34], [17, 23], [17, 49], [18, 43], [18, 83], [18, 85], [18, 86],
  [19, 32], [19, 46], [19, 87], [19, 89], [20, 92], [21, 96], [22, 97], [22, 103],
  [23, 17], [23, 50], [24, 66], [24, 70], [25, 64], [25, 71],
  [26, 40], [26, 65], [26, 70], [26, 75], [27, 75], [28, 29], [28, 30], [28, 44],
  [29, 30], [30, 31], [30, 32], [30, 33], [30, 44], [30, 61], [30, 88], [30, 93],
  [31, 32], [31, 61], [32, 87], [32, 100], [32, 120], [32, 164],
  [33, 88], [33, 90], [33, 92], [34, 16], [34, 92],
  [35, 37], [35, 38], [35, 39], [35, 48], [36, 37], [36, 127],
  [37, 38], [37, 67], [37, 69], [37, 104], [37, 114], [38, 39], [38, 109],
  [39, 96], [39, 107], [40, 26], [40, 75], [40, 155],
  [41, 80], [41, 147], [41, 148], [42, 9], [42, 41],
  [43, 18], [43, 85], [44, 45], [44, 61], [45, 47], [45, 72],
  [46, 19], [46, 87], [47, 65], [48, 35], [48, 79], [48, 82],
  [49, 50], [49, 52], [50, 54], [51, 60], [51, 120], [52, 53], [52, 55], [52, 56],
  [53, 110], [54, 55], [55, 56], [55, 120], [57, 68], [57, 73], [57, 85], [57, 86],
  [58, 63], [59, 115], [59, 176], [60, 67], [60, 68], [60, 171],
  [61, 62], [61, 69], [61, 119], [61, 125], [62, 63], [63, 58],
  [64, 71], [64, 25], [65, 75], [65, 155], [66, 70], [66, 134],
  [67, 37], [67, 68], [67, 114], [68, 73], [68, 137], [69, 115], [69, 161], [69, 163],
  [70, 66], [71, 25], [71, 176], [72, 60], [73, 57], [74, 75],
  [75, 76], [75, 77], [75, 78], [75, 79], [76, 79], [76, 129], [77, 79], [77, 136], [78, 79], [78, 141],
  [79, 80], [79, 81], [80, 41], [80, 148], [81, 44], [82, 41], [82, 148], [82, 151],
  [83, 148], [83, 157], [84, 85], [84, 154], [85, 18], [85, 43], [86, 75], [86, 137],
  [87, 88], [87, 89], [87, 165], [88, 100], [88, 124], [88, 165], [89, 93], [90, 33], [91, 34], [91, 153], [92, 16], [93, 88],
  // Buildings: from site to house
  [95, 96], [95, 99], [95, 100], [95, 102], [95, 104], [95, 106], [95, 108],
  [96, 21], [96, 107], [97, 103], [98, 131], [98, 132], [99, 110], [100, 121], [100, 122], [100, 124],
  [101, 100], [101, 119], [102, 110], [102, 130], [103, 22], [103, 97], [104, 105], [104, 106], [104, 114],
  [105, 106], [105, 161], [106, 107], [106, 114], [106, 115], [107, 109], [107, 115], [107, 159],
  [108, 106], [108, 119], [109, 127], [110, 112], [110, 130], [110, 242], [111, 110], [111, 171],
  [112, 110], [112, 130], [112, 134], [113, 97], [113, 110], [114, 115], [114, 163],
  [115, 106], [115, 171], [116, 117], [117, 209], [117, 232], [118, 117], [118, 175],
  [119, 100], [119, 166], [119, 167], [119, 244],
  [120, 121], [120, 122], [121, 124], [121, 125], [122, 164], [122, 165],
  [123, 61], [123, 124], [124, 125], [124, 179], [125, 241],
  [126, 127], [126, 185], [127, 128], [127, 129], [127, 130], [127, 136], [127, 137], [127, 141],
  [128, 159], [128, 161], [128, 180], [129, 139], [129, 147], [129, 181], [129, 182],
  [130, 110], [130, 112], [130, 149], [131, 132], [131, 191], [132, 130], [133, 158], [133, 166],
  [134, 180], [134, 192], [135, 180], [135, 238], [135, 252],
  [136, 187], [136, 188], [136, 189], [137, 138], [137, 143], [137, 203],
  [138, 188], [139, 147], [139, 184], [139, 199], [140, 160], [140, 165], [140, 242],
  [141, 142], [141, 179], [141, 180], [141, 183], [142, 151], [142, 179],
  [143, 137], [143, 188], [144, 136], [144, 189], [145, 157], [145, 198],
  [146, 148], [146, 151], [146, 152], [147, 139], [147, 182], [148, 151], [148, 152],
  [149, 130], [149, 150], [150, 124], [150, 179], [151, 152], [151, 179], [152, 183],
  [153, 79], [153, 154], [154, 84], [154, 141], [155, 40], [155, 154],
  [156, 79], [156, 157], [157, 156], [157, 83], [157, 145],
  [158, 131], [158, 133], [159, 128], [159, 180], [159, 192], [159, 194], [160, 107], [160, 164], [160, 167], [160, 202],
  [161, 105], [161, 163], [161, 180], [162, 104], [162, 157], [163, 106], [163, 115], [163, 119], [163, 244],
  [164, 165], [164, 180], [164, 192], [165, 140], [165, 166],
  [166, 165], [167, 119], [167, 166], [168, 104], [168, 215],
  [169, 104], [169, 170], [170, 171], [170, 177], [171, 172], [171, 173], [172, 176],
  [173, 174], [173, 245], [174, 163], [174, 246], [175, 118], [175, 177],
  [176, 172], [176, 180], [177, 178], [177, 184], [178, 177], [178, 247],
  [179, 180], [179, 188], [179, 202], [180, 181], [180, 182], [180, 202], [180, 221], [180, 222],
  [181, 129], [181, 139], [182, 139], [182, 147], [182, 250], [182, 252],
  [183, 141], [183, 152], [183, 180], [184, 139], [184, 199], [184, 201],
  [185, 142], [185, 181], [186, 187], [187, 188], [188, 202], [189, 136], [189, 144],
  [190, 191], [190, 192], [190, 220], [191, 192], [191, 193], [191, 196],
  [192, 194], [193, 196], [194, 195], [194, 159], [195, 133], [195, 158],
  [196, 131], [197, 179], [197, 180], [197, 198], [197, 200], [197, 211],
  [198, 145], [198, 200], [199, 184], [199, 180], [200, 201], [200, 145],
  [201, 202], [202, 141], [202, 180], [203, 204], [203, 137], [204, 203],
  // Construction
  [205, 206], [205, 213], [205, 209], [206, 208], [206, 207],
  [207, 208], [207, 234], [207, 248], [208, 209], [208, 210],
  [209, 210], [209, 211], [210, 211], [210, 219], [210, 229],
  [211, 212], [211, 197], [212, 213], [212, 216], [212, 226], [213, 214],
  [214, 215], [215, 168], [216, 217], [216, 229], [217, 218], [217, 219],
  [218, 219], [218, 234], [218, 235], [219, 220], [219, 228],
  [220, 117], [220, 231], [220, 232], [221, 222], [221, 223], [221, 225],
  [222, 180], [222, 223], [223, 225], [223, 238], [224, 112], [224, 225],
  [225, 240], [226, 212], [226, 227], [227, 249], [228, 195], [228, 158],
  [229, 230], [230, 215], [230, 252], [231, 204], [231, 220],
  [232, 117], [233, 204], [233, 248], [234, 207], [235, 207], [236, 221], [236, 180],
  [237, 110], [237, 221], [238, 135], [238, 174], [238, 239],
  [239, 223], [239, 236], [240, 225], [240, 249],
  [241, 125], [241, 202], [241, 243], [242, 110], [242, 140], [242, 241],
  [243, 241], [243, 173], [244, 119], [244, 163],
  [245, 173], [245, 177], [246, 174], [246, 170], [247, 68], [247, 247],
  [248, 207], [248, 233], [249, 227], [249, 240],
  [250, 135], [250, 251], [250, 252], [251, 252], [251, 253], [252, 135], [252, 230], [253, 204],
];
